### ISSUE TITLE
selectedDateTime is not set with initialDateTime on initialization

### ISSUE THREAD

**Issue by evaranshark** [koukibadr/Bottom-Picker#25]
If you open BottomPicker with initial date provided, you will see the correct value on picker. But if you don't change selected date, onSubmit will return DateTime.now() instead of initialDateTime.

The problem is, probably, in _BottomPickerState.initState() method.

**Comment by koukibadr** [comment]
Thanks @evaranshark  for providing exact problem description, it will be fixed ASAP and published in a new version

**Comment by koukibadr** [comment]
@evaranshark the package is now up to date with the bug fixes check it out 1.0.6
