### ISSUE TITLE
locale support

### ISSUE THREAD

**Issue by YeFei572** [koukibadr/Bottom-Picker#28]
Hello， this plugin can locale support?

**Comment by koukibadr** [comment]
For now you can choose between 24h format or 12h format (AM/PM) but we will add format parameter and locale support in the next version

**Comment by YeFei572** [comment]
Alright, I have advice about the format of the date, I need the date list like this: 2021-12, just remove the day about the format, can support this plugin? 
thx!

**Comment by koukibadr** [comment]
No for now it can't be done once we add the date format parameter you can choose the format you want 
but as a workaround you can get the date from bottom_picker and then reformat it into the date format you want

**Comment by koukibadr** [comment]
@YeFei572 I added a date format order attribute to the widget bottom picker in the newest version 1.0.4 and may help you achieve what you want to do check it out [https://pub.dev/packages/bottom_picker](https://pub.dev/packages/bottom_picker)

**Comment by YeFei572** [comment]
Good job！thx
