### ISSUE TITLE
Requesting a backgroundColor property

### ISSUE THREAD

**Issue by willypede** [koukibadr/Bottom-Picker#29]
It would be amazing to have this property for apps with Dark Mode feature.

**Comment by koukibadr** [comment]
@willypede thanks for your feedback, it will b available in the next version of the package

**Comment by willypede** [comment]
@koukibadr Nicee, looking forward for the next version! God bless

**Comment by koukibadr** [comment]
@willypede a new version has been published with possibility to change the background now check it out

**Comment by willypede** [comment]
@koukibadr I have tried it, backgroundColor works like charm! And now I have another request: textColor property for the picker text color. Should I close this issue and open a new one?
![image](https://user-images.githubusercontent.com/45930114/146728385-71cdc7d8-a856-4313-95e6-c74270788341.png)

**Comment by koukibadr** [comment]
@willypede happy for the good news about background 
Yes please it would be better if we open a new issue
