### ISSUE TITLE
Requesting color property for X button (top right)

### ISSUE THREAD

**Issue by willypede** [koukibadr/Bottom-Picker#35]

**Comment by koukibadr** [comment]
Thanks for the proposition I will work on it

**Comment by koukibadr** [comment]
Color property is now available in the new version 1.5.0 check it out
[https://pub.dev/packages/bottom_picker](https://pub.dev/packages/bottom_picker)

**Comment by willypede** [comment]
It's working perfectly. Great work! I have another request and I will post it soon.
