### ISSUE TITLE
No range (padding) between title, datepicker, and button

### ISSUE THREAD

**Issue by willypede** [koukibadr/Bottom-Picker#40]
![image](https://user-images.githubusercontent.com/45930114/151704040-e8df34d3-89f7-4c7d-8cc6-f89fd97b8c87.png)
Something like padding property for the picker would be great

**Comment by koukibadr** [comment]
thanks for  your review @willypede  I will work on it

**Comment by koukibadr** [comment]
@willypede the issue is fixed it will be available in the next version

**Comment by koukibadr** [comment]
The modifications are now available in the version 1.6.0
[https://pub.dev/packages/bottom_picker](https://pub.dev/packages/bottom_picker)
