### ISSUE TITLE
Height issue on OnePlus Nord Phone

### ISSUE THREAD

**Issue by MustafaDev-shaikh** [koukibadr/Bottom-Picker#44]
![photo_2022-02-16_19-11-49](https://user-images.githubusercontent.com/62279606/154276818-1d37d558-9bf0-47a0-9966-75cdfb8b1bc8.jpg)
 
if possible give height parameters so we can adjust

**Comment by koukibadr** [comment]
@MustafaDev-shaikh thanks for your feedback 
I just published a new version (1.7.0) contains the height parameter check it out
[https://pub.dev/packages/bottom_picker](https://pub.dev/packages/bottom_picker)

**Comment by Mustafa74Dev** [comment]
@koukibadr  Thanks man now it's work perfect. 
quick fix and fast response
