### ISSUE TITLE
iOS - SafeArea

### ISSUE THREAD

**Issue by bschrdr** [koukibadr/Bottom-Picker#45]
Picker ignores iOS SafeArea.
<img width="458" alt="Bildschirmfoto 2022-02-17 um 19 48 33" src="https://user-images.githubusercontent.com/37639587/154550128-8debb159-bffb-4903-b01f-2e1d63c0da90.png">

**Comment by koukibadr** [comment]
Issue fixed in the latest versions @bschrdr if you still face this problem you can reopen this issue or create a new one
