### ISSUE TITLE
Datetime picker not show data

### ISSUE THREAD

**Issue by TechnoPrashant** [koukibadr/Bottom-Picker#46]
![1645679696505 (1)](https://user-images.githubusercontent.com/7537622/155468478-51749b6a-e9ab-43b3-90d6-03f7c15792aa.JPEG)

**Comment by koukibadr** [comment]
Hello @TechnoPrashant can you please provide more information about this bug for example the code snippet ?

**Comment by TechnoPrashant** [comment]
It required to add for old devices. 
pickerTextStyle: TextStyle(
              color: Colors.black,
            ),
