### ISSUE TITLE
Close IconButton and button for onSubmit should be nullable

### ISSUE THREAD

**Issue by georonathan47** [koukibadr/Bottom-Picker#47]
I used the package in a project. However, I wanted to not show the buttons (close and submit buttons) to the user.
Can there be changes made to the package so that it supports nullable features for the developer to decide whether to show it or not?

I think that will be a great feature to introduce!

**Comment by koukibadr** [comment]
Thanks for you feedback @georonathan47 I will work on it

**Comment by koukibadr** [comment]
@georonathan47  You can now hide the submit button with the latest version 
check it out: [https://pub.dev/packages/bottom_picker](https://pub.dev/packages/bottom_picker)

**Comment by georonathan47** [comment]
👍😃👍 great
