### ISSUE TITLE
Please add a SelectableDayPredicate

### ISSUE THREAD

**Issue by zAlweNy26** [koukibadr/Bottom-Picker#51]
I really like your package, but it needs something like the SelectableDayPredicate to be a 10 out of 10. If you could add it to filter days, months, years and hours, it would be fantastic!

**Comment by koukibadr** [comment]
@zAlweNy26 thanks a lot for your support!
I will work on it once it's ready to use I will let you know

**Comment by zAlweNy26** [comment]
@koukibadr thank you very much for the attention, I also suggest adding a setting to define minutes interval, it should be easy to add as it already exist in the CupertinoDatePicker you use!
![image](https://user-images.githubusercontent.com/41266342/168256283-efb7483f-6b72-46f1-a69d-a83e1a6792ae.png)

**Comment by zAlweNy26** [comment]
Sorry to bother you again, but I saw a grammatical error in your code, I don't know if you already know this and you will fix it in the next package version, but to be sure I wanted to warn you about it.
![image](https://user-images.githubusercontent.com/41266342/168259120-f15af6c6-44d6-4a54-8838-6a525c1151f3.png)

**Comment by koukibadr** [comment]
@zAlweNy26 thanks for your feedbacks I will work on them

**Comment by fareesh** [comment]
Fix for the typo: https://github.com/koukibadr/Bottom-Picker/pull/54

**Comment by fareesh** [comment]
Added a proposed solution to wrap `minuteInterval` option in `CupertinoDatePicker`. If `initialDateTime` is not supplied, the error below will be triggered in its present form. 

> @koukibadr thank you very much for the attention, I also suggest adding a setting to define minutes interval, it should be easy to add as it already exist in the CupertinoDatePicker you use! ![image](https://user-images.githubusercontent.com/41266342/168256283-efb7483f-6b72-46f1-a69d-a83e1a6792ae.png) Also, pay attention to this problem about minuteInterval : https://stackoverflow.com/questions/62590945/setting-cupertinodatepicker-minuteinterval-throws-an-exception-flutter

**Comment by koukibadr** [comment]
@zAlweNy26 I just merged @fareesh's PR contains all the necessary modifications I will let you know once it's published

**Comment by zAlweNy26** [comment]
Beautiful, thank you all a lot for your work !
