### ISSUE TITLE
InitialDateTime for minute Time Picker

### ISSUE THREAD

**Issue by quocviet1996** [koukibadr/Bottom-Picker#66]
So i can init the default time with InitialDateTime like this, but only hour is change, minute always init 0 no matter what number i choose
![image](https://github.com/koukibadr/Bottom-Picker/assets/48380821/374175b7-805d-4026-91e5-e02832b8df43)
![image](https://github.com/koukibadr/Bottom-Picker/assets/48380821/61dcdcfb-8eb0-490a-b1ca-7a8fd0723856)

**Comment by AhmedAElllatif** [comment]
same

**Comment by koukibadr** [comment]
The version 2.3.1 just published check it out
for `time` constructor now you need to set the `initalTime` with the `Time` class
example
```Dart
BottomPicker.time(
      title: 'Set your next meeting time',
      titleStyle: TextStyle(
        fontWeight: FontWeight.bold,
        fontSize: 15,
        color: Colors.orange,
      ),
      onSubmit: (index) {
        print(index);
      },
      onClose: () {
        print('Picker closed');
      },
      bottomPickerTheme: BottomPickerTheme.orange,
      use24hFormat: true,
      initialTime: Time(
        minutes: 23,
      ),
      maxTime: Time(
        hours: 17,
      ),
    ).show(context);
```
