### ISSUE TITLE
Feature request : Modify Button size

### ISSUE THREAD

**Issue by dupiesdupreez** [koukibadr/Bottom-Picker#68]
A way to modify the button size would be great, since making the text bigger just makes it overflow.

![image](https://github.com/koukibadr/Bottom-Picker/assets/6910085/82982a3d-655f-49f7-9535-40e6a234b7b5)

**Comment by koukibadr** [comment]
@dupiesdupreez this new feature has been deployed with the latest bottom_picker version

**Comment by koukibadr** [comment]
@dupiesdupreez feel free to close the issue if the latest version fix the problem you had in your app
