### ISSUE TITLE
Whether a range time exists

### ISSUE THREAD

**Issue by leessmin** [koukibadr/Bottom-Picker#93]
Now I can see that date ranges already exist, so why not add a time range

**Comment by koukibadr** [comment]
@leessmin it could be a nice feature to have, I'll work on it but if you have a PR on that it would be amazing to contribute on this project

**Comment by leessmin** [comment]
Thanks you for your answer, I happen to have this idea

**Comment by koukibadr** [comment]
Feel free to contribute to this project
you'll have your account displayed in the package page on pub.dev 😅
